# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1

commands:
  install_sdk:
    description: "Install the DAML SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          command: |
            cd ${HOME}
            wget https://github.com/digital-asset/daml/releases/download/v<< parameters.version >>/daml-sdk-<< parameters.version >>-linux.tar.gz
            tar -zxvf daml-sdk-<< parameters.version >>-linux.tar.gz
            cd sdk-<< parameters.version >>
            ./install.sh
            cd ${HOME}
            rm -rf sdk-<< parameters.version >>

jobs:
  build:
    parameters:
      daml_sdk_version:
        type: string
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache sbt dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
           name: Build
           command: |
             export PATH=${HOME}/.daml/bin:${PATH}
             make build
      - run:
           name: Test
           command: |
             export PATH=${HOME}/.daml/bin:${PATH}
             make test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

  release_to_github:
    parameters:
      daml_sdk_version:
        type: string
    docker:
      - image: circleci/openjdk:11.0-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache sbt dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          name: release-jar-to-github
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            SHA=$(git rev-parse HEAD)
            VERSION="0.0.0-snapshot-$(git show -s --format=%cd --date=format:%Y%m%d HEAD).$(git rev-list --count HEAD).$(git show -s --format=%h --abbrev=8 HEAD)"
            sed -i "s/version :=.*/version := \"$VERSION\"/" build.sbt
            make assembly
            git checkout build.sbt

            RELEASE_DIR=$(mktemp -d)
            cp target/scala-2.12/authentication-service-assembly-$VERSION.jar $RELEASE_DIR/ref-ledger-authenticator-$VERSION.jar
            cd $RELEASE_DIR
            sha256sum $(find . -type f | sort) > sha256sums


            KEY_FILE=$(mktemp)
            GPG_DIR=$(mktemp -d)
            cleanup() {
                rm -rf $KEY_FILE $GPG_DIR
            }
            trap cleanup EXIT
            echo "$GPG_CODE_SIGNING" | base64 -d > $KEY_FILE
            gpg --homedir $GPG_DIR --no-tty --quiet --import $KEY_FILE

            for f in *; do
                gpg --homedir $GPG_DIR -ab $f
            done

            RESPONSE=$(curl --fail \
                            --silent \
                            --location \
                            -H "Authorization: token $GITHUB_TOKEN" \
                            --data "{\"tag_name\": \"v$VERSION\", \"name\": \"$VERSION\", \"body\": \"Automated release.\", \"target_commitish\": \"$SHA\"}" \
                            https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases)

            UPLOAD_URL="$(echo "$RESPONSE" | jq -r .upload_url | sed -e "s/{?name,label}//")"

            for f in *; do
                curl -H "Content-Type: application/zip" \
                     --include \
                     --fail \
                     --silent \
                     --location \
                     -H "Authorization: token $GITHUB_TOKEN" \
                     --data-binary "@$f" \
                     "${UPLOAD_URL}?name=$f"
            done
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

  blackduck_scan:
    parameters:
      daml_sdk_version:
        type: string
    docker:
      - image: circleci/openjdk:11.0-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache sbt dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
           name: Build
           command: |
             export PATH=${HOME}/.daml/bin:${PATH}
             make build
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
            ci-build digitalasset_ref-ledger-authenticator master \
            --logging.level.com.synopsys.integration=DEBUG \
            --detect.excluded.detector.types=SBT \
            --detect.notices.report=true \
            --detect.cleanup=false \
            --detect.cleanup.bdio.files=false \
            --detect.report.timeout=1000 \
      - store_artifacts:
          path: /home/circleci/blackduck/runs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          daml_sdk_version: "1.2.0"
      - release_to_github:
          daml_sdk_version: "1.2.0"
          filters:
            branches:
              only: master

  blackduck:
    triggers:
      - schedule:
          cron: "0 8 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - blackduck_scan:
          daml_sdk_version: "1.2.0"
          context: blackduck
